#!/usr/bin/lua

string1="hello WORLD"
print("orign string1:" .. string1)
string2=string.upper(string1)
print("after upper string1:" .. string2)
string3=string.lower(string1)
print("after lower string1:" .. string3)
string4=string.gsub(string1,"lo","AA")
print("after lower string1:" .. string4)
string5=string.gsub(string1,"l","A",2)
print("after lower string1:" .. string5)
string6=string.find(string1,"l",2,6)
print("after lower string1:" .. string6)
string7=string.reverse(string1)
print("after lower string1:" .. string7)
string8=string.format("str:%d",8)
print("after lower string1:" .. string8)
string9=string.char(97,98,99,100)
print("after lower string1:" .. string9)
string9=string.byte("ABCD",4)
print("after lower string1:" .. string9)
string9=string.byte("ABCD")
print("after lower string1:" .. string9)
string9=string.len("ABCD")
print("after lower string1:" .. string9)
string9=string.byte("ABCD")
print("after lower string1:" .. string9)
string9=string.rep("ABCD",2)
print("after lower string1:" .. string9)
